### ISSUE TITLE
WLC C9800 is detected with SNMP Class: SNMP::Info::Layer3::Cisco

### ISSUE THREAD

**Issue by cbandicot** [netdisco/snmp-info#435] opened 2021-08-26 13:17 UTC
## Current Behavior

The WLC C9800 is detected with SNMP::Info::Layer3::Cisco instead of SNMP::Info::Layer2::Airespace

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Device

* Vendor: Cisco 
* Device Model: C980040K9
* Operating System Version: ios-xe  / 16.12.4a
* Snmpwalk output of .1.3.6.1.2.1.1:

## Your Environment

* SNMP::Info version used: 3.73
* Netdisco version (if used): 2.49.1

**Comment by inphobia** [comment] 2021-09-02 21:59
this is most likely since sysobjectid or sysdescr doesn't match. can you give an snmpwalk of .1.3.6.1.2.1.1 ?

also, it seems 9800 series have their mibs restricted without a support contract, that will most likekly be the next hurdle.

**Comment by inphobia** [comment] 2021-09-02 22:10
duplicate of #436 which has more info.

**Closed by inphobia** 2021-09-02 22:10 UTC
Labels: duplicate
