### ISSUE TITLE
Avaya ERS4900 series switch port numbering error.

### ISSUE THREAD

**Issue by jl84** [netdisco/snmp-info#238] opened 2017-12-06 08:37 UTC
## Expected Behavior
Adding a new ERS4900 switch should all every every device in the ports-list from switch 1 to 8

## Current Behavior
Adding a ERS4900 switch causes Netdisco to skip devices 5-8 and instead add device 1-4 with switch numbering 1,3,5,7. Under Modules all 8 devices are visible but not in the ports-list. 

## Possible Solution
When Avaya introduced the ERS4900 and 5900 series (Same firmware) they added a 59100 model with 100 ports, this probably has something to do with devices not being added correctly and Netdisco considering device 2 as 3, 3 as 5 and so on. 

## Context
The second half of the switches in the stack are not visible in the ports-list and the port numbering error makes device discovery problematic and can cause config errors.

## Your Environment
Software	        Version
App::Netdisco	2.36.11 (Had same issue in a few previous versions)
SNMP::Info	3.37
DB Schema	44
PostgreSQL	8.4.20
Perl		        5.10.1

![image](https://user-images.githubusercontent.com/27852669/33652135-8806f964-da68-11e7-86e7-eab9ad85cb3f.png)

![image](https://user-images.githubusercontent.com/27852669/33652185-ba30131c-da68-11e7-93fa-a892b2f29955.png)

**Comment by zoeloe** [comment] 2018-01-16 22:40
FYI:
Suggested intermediate fix:
It seems that a 4950 switch has a index_factor of 128.
It looks that modifying SNMP::Info::Layer2::Baystack.pm

the diff is e.g.:
```
----------------
232c232
<         if ( ( $model =~ /(5[56]\d\d)|VSP|(4950)/ )
---
>         if ( ( $model =~ /(5[56]\d\d)|VSP/ )
----------------
```

does the trick.
It would be nice if a generic catch-all fix would be available. A similar regex would catch
other devices with an index_factor of 128.

**Comment by jl84** [comment] 2018-01-18 12:18
I owe you a beer, this worked perfectly, thank you!

**Comment by jl84** [comment] 2018-01-18 12:19
I owe you a beer, this worked perfectly, thank you!

**Comment by ollyg** [comment] 2018-02-12 22:16
fixed in 4afbd37, many thanks!

**Closed by ollyg** 2018-02-12 22:16 UTC

**Comment by t350** [comment] 2020-04-02 13:27
Hello,,

How did you solved this issue?
Can you explain please step by step?
Thanks in advance!

I have opened my issue, you can see my issue in the below link.
I have both models 4950 and 5900 but the issue is only on 5900, even if they have same firmware.
https://github.com/netdisco/netdisco/issues/709

**Comment by zoeloe** [comment] 2020-04-02 19:17
Ollyg changed some code, not me reaaly , I suggested some intermediate patch in:
https://github.com/netdisco/snmp-info/issues/239
it's the regex that is important:
Ollyg code: https://github.com/netdisco/snmp-info/commit/4afbd37cbd141b4fbcd05ecb4fa9bbb8b9882be8
to test regex see: https://regex101.com

**Comment by t350** [comment] 2020-04-03 09:25
Hi,

Line 231 looks:
if ( ( $model =~ /(5[56]\d\d)|VSP|4950|59100/ )

and i did this change:
if ( ( $model =~ /(5[56]\d\d)|VSP|4950|5952/ )

Now it works the ports are displayed correct.
I hope that i didnt do anything wrong :) 
Thanks alot!

**Comment by jl84** [comment] 2020-05-28 07:00
Hi,

The 50 port switches work now but the 4926 doesn't. Both in a mixed stack with both 4926 and 4950 and in stacks with only 4926

![image](https://user-images.githubusercontent.com/27852669/83109161-2f3ed280-a0c1-11ea-9586-aacd1e5e93ac.png)
