### ISSUE TITLE
SNMP-info does not provide correct neighbours information

### ISSUE THREAD

**Issue by def-bs** [netdisco/snmp-info#268] opened 2018-06-08 13:45 UTC
## Expected Behavior
 I expect to make a query via SNMP and obtain the  neighbours devices, like, the nearby switches.

## Current Behavior
I don't get the correct information for some devices.

## Possible Solution
I opened an issue on netdisco at this link: https://github.com/netdisco/netdisco/issues/386 
But they were unable to help, they suggested to open an issue here. 

## Context
Without the correct information, netdisco is unable to show nearby switches, I get the following error: Your data contains an empty nodes array.

## Your Environment
App::Netdisco	2.39.30
SNMP::Info	3.60

Thank you for your help.
Best Regards.

**Comment by def-bs** [comment] 2018-06-08 13:52
For example, on a working device i get this:

~netdisco/bin/netdisco-do show -DI -d 10.20.255.152 -e c_ip
[28267] 2018-06-08 13:50:03  info App::Netdisco version 2.039030 loaded.
[28267] 2018-06-08 13:50:03  info show: [10.20.255.152]/c_ip started at Fri Jun  8 15:50:03 2018
[28267] 2018-06-08 13:50:03 debug show: running with timeout 600s
[28267] 2018-06-08 13:50:03 debug => running workers for phase: check
[28267] 2018-06-08 13:50:03 debug -> run worker check/_base_/0
[28267] 2018-06-08 13:50:03 debug Show is able to run
[28267] 2018-06-08 13:50:03 debug => running workers for phase: main
[28267] 2018-06-08 13:50:03 debug -> run worker main/_base_/100
[28267] 2018-06-08 13:50:03 debug snmp reader cache warm: [10.20.255.152]
[28267] 2018-06-08 13:50:03 debug [10.20.255.152:161] try_connect with ver: 2, class: SNMP::Info::Layer2::HP, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.60
SNMP::Info::device_type() layers:01001010 id:11 sysDescr:"ProCurve J9088A Switch 2610-48, revision R.11.72, ROM R.10.06 (/sw/code/build/nemo(R_ndx))"
SNMP::Info::_global lldp_sys_cap : LLDP-MIB::lldpLocSysCapEnabled.0 : .1.0.8802.1.1.2.1.3.6.0
SNMP::Info::_global cdp_run : CISCO-CDP-MIB::cdpGlobalRun.0 : .1.3.6.1.4.1.9.9.23.1.3.1.0
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_load_attr lldp_rman_addr : LLDP-MIB::lldpRemManAddrIfSubtype : .1.0.8802.1.1.2.1.4.2.1.3
SNMP::Info::_load_attr cdp_addr : CISCO-CDP-MIB::cdpCacheAddress : .1.3.6.1.4.1.9.9.23.1.2.1.1.4
SNMP::Info::_load_attr cdp_proto : CISCO-CDP-MIB::cdpCacheAddressType : .1.3.6.1.4.1.9.9.23.1.2.1.1.3
\ {
    0.50.1   "10.23.252.8",
    50.1     "10.23.252.8"
}
[28267] 2018-06-08 13:50:04  info show: finished at Fri Jun  8 15:50:04 2018
[28267] 2018-06-08 13:50:04  info show: status done: Showed c_ip response from 10.20.255.152




And it is working fine. But, on another device I get this:
 ~netdisco/bin/netdisco-do show -DI -d 10.33.0.22 -e c_ip
[28323] 2018-06-08 13:51:17  info App::Netdisco version 2.039030 loaded.
[28323] 2018-06-08 13:51:18  info show: [10.33.0.22]/c_ip started at Fri Jun  8 15:51:18 2018
[28323] 2018-06-08 13:51:18 debug show: running with timeout 600s
[28323] 2018-06-08 13:51:18 debug => running workers for phase: check
[28323] 2018-06-08 13:51:18 debug -> run worker check/_base_/0
[28323] 2018-06-08 13:51:18 debug Show is able to run
[28323] 2018-06-08 13:51:18 debug => running workers for phase: main
[28323] 2018-06-08 13:51:18 debug -> run worker main/_base_/100
[28323] 2018-06-08 13:51:18 debug snmp reader cache warm: [10.33.0.22]
[28323] 2018-06-08 13:51:18 debug [10.33.0.22:161] try_connect with ver: 2, class: SNMP::Info::Layer2::HP, comm: <hidden>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.60
SNMP::Info::device_type() layers:01001010 id:11 sysDescr:"HP J9565A Switch 2615-8-PoE, revision A.15.16.0021, ROM J.14.08 (/ws/swbuildm/maint_orlando_qaoff/code/build/lgr(swbuildm_maint_orlando_qaoff_maint_orlando)) (Formerly ProCurve)"
SNMP::Info::_global lldp_sys_cap : LLDP-MIB::lldpLocSysCapEnabled.0 : .1.0.8802.1.1.2.1.3.6.0
SNMP::Info::_global cdp_run : CISCO-CDP-MIB::cdpGlobalRun.0 : .1.3.6.1.4.1.9.9.23.1.3.1.0
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_load_attr lldp_rman_addr : LLDP-MIB::lldpRemManAddrIfSubtype : .1.0.8802.1.1.2.1.4.2.1.3
SNMP::Info::_load_attr cdp_addr : CISCO-CDP-MIB::cdpCacheAddress : .1.3.6.1.4.1.9.9.23.1.2.1.1.4
SNMP::Info::_load_attr cdp_proto : CISCO-CDP-MIB::cdpCacheAddressType : .1.3.6.1.4.1.9.9.23.1.2.1.1.3
\ {}
[28323] 2018-06-08 13:51:18  info show: finished at Fri Jun  8 15:51:18 2018
[28323] 2018-06-08 13:51:18  info show: status done: Showed c_ip response from 10.33.0.22


It doesn't seem able to get the information needed.

**Comment by def-bs** [comment] 2018-06-08 13:56
In the following image, you can see some of the devices that are not shown correctly.

![unconnecteddevices](https://user-images.githubusercontent.com/31916347/41161862-736d64a4-6b34-11e8-9f21-2d05667f21f0.png)

**Comment by inphobia** [comment] 2018-10-26 20:36
might be similar to: https://github.com/netdisco/netdisco/issues/436

as far i as understand netdisco requires interface names and ip addresses to match on both ends (cdp or lldp) before it considers devices to be linked.
for example, aerohive wireless access points advertise interface mgt0 (== logical interface) as their management interface, but on cisco ios switches they are detected on their physical interface, eth0 or 1. as such the access point & switch data do not match & no link will be made.
the abovementioned issue has a patch that makes my aerohive, cisco ucs server & vmware esx devices link up. thus far i have not seen any regressions while using it.

**Comment by def-bs** [comment] 2019-03-05 10:24
I see.

But it is a issue on my side, bad configuration?

This devices have interface names and ip addresses that do not match on both ends (cdp or lldp) 

Is there something that I can do?

Thank you.

**Comment by JeroenvIS** [comment] 2019-03-05 14:21
> as far i as understand netdisco requires interface names and ip addresses to match on both ends (cdp or lldp) before it considers devices to be linked.

From the data provided in the bug report, there's no indication (yet) that this is the cause for the problem.

@def-bs Maybe the "problematic" switch doesn't report neighbour IP addresses.

1) What does "show cdp neigh detail" say on the CLI, for switch 10.33.0.22? Does it show IP addresses for neighbors?
2) When you ask netdisco-do to show 'c_id' and 'cdp_proto' on 10.33.0.22, what are the outputs?

**Comment by def-bs** [comment] 2019-03-05 14:28
~netdisco/bin/netdisco-do show -DI -d 10.33.0.22 -e c_id
[5221] 2019-03-05 14:27:56  info App::Netdisco version 2.040006 loaded.
[5221] 2019-03-05 14:27:57  info show: [10.33.0.22]/c_id started at Tue Mar  5 15:27:57 2019
[5221] 2019-03-05 14:27:57 debug show: running with timeout 600s
[5221] 2019-03-05 14:27:57 debug => running workers for phase: check
[5221] 2019-03-05 14:27:57 debug -> run worker check/_base_/0
[5221] 2019-03-05 14:27:57 debug Show is able to run
[5221] 2019-03-05 14:27:57 debug => running workers for phase: main
[5221] 2019-03-05 14:27:57 debug -> run worker main/_base_/100
[5221] 2019-03-05 14:27:57 debug snmp reader cache warm: [10.33.0.22]
[5221] 2019-03-05 14:27:57 debug [10.33.0.22:161] try_connect with ver: 2, class: SNMP::Info::Layer2::HP, comm: <hid          den>
SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global layers : SNMPv2-MIB::sysServices.0 : .1.3.6.1.2.1.1.7.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.65
SNMP::Info::device_type() layers:01001010 id:11 sysDescr:"HP J9565A Switch 2615-8-PoE, revision A.15.16.0021, ROM J.          14.08 (/ws/swbuildm/maint_orlando_qaoff/code/build/lgr(swbuildm_maint_orlando_qaoff_maint_orlando)) (Formerly ProCur          ve)"
SNMP::Info::_global lldp_sys_cap : LLDP-MIB::lldpLocSysCapEnabled.0 : .1.0.8802.1.1.2.1.3.6.0
SNMP::Info::_global cdp_run : CISCO-CDP-MIB::cdpGlobalRun.0 : .1.3.6.1.4.1.9.9.23.1.3.1.0
SNMP::Info::_validate_autoload_method(hasSONMP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasFDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasEDP) Unable to resolve method.
SNMP::Info::_validate_autoload_method(hasAMAP) Unable to resolve method.
SNMP::Info::_load_attr lldp_rem_id_type : LLDP-MIB::lldpRemChassisIdSubtype : .1.0.8802.1.1.2.1.4.1.1.4
SNMP::Info::_load_attr lldp_rem_id : LLDP-MIB::lldpRemChassisId : .1.0.8802.1.1.2.1.4.1.1.5
SNMP::Info::_load_attr cdp_dev_id : CISCO-CDP-MIB::cdpCacheDeviceId : .1.3.6.1.4.1.9.9.23.1.2.1.1.6
\ {}
[5221] 2019-03-05 14:27:58  info show: finished at Tue Mar  5 15:27:58 2019
[5221] 2019-03-05 14:27:58  info show: status done: Showed c_id response from 10.33.0.22

**Comment by JeroenvIS** [comment] 2019-03-05 15:04
OK, so this specific 2615 doesn't list any CDP neighbours when queried via SNMP. How about the CLI, are the neighbours listed there?

**Comment by def-bs** [comment] 2019-03-05 15:05
Sorry, what command should I use for show cdp neigh detail

**Comment by JeroenvIS** [comment] 2019-03-05 15:08
I mean on the switch command line interface . So log in to the switch via Telnet or SSH and then give the command "show cdp neigh detail".

Since the switch isn't showing any neighbours when queried via SNMP, it's better to double check whether it actually knows what neighbours it has.

**Comment by def-bs** [comment] 2019-03-12 13:33
Sorry for the late answer.

The devices are not visible with show cdp neigh detail.

Most of problems is on 3COM router and Wifi Controller.

Could be that the 3COm are too old?

**Comment by JeroenvIS** [comment] 2019-03-12 14:29
OK, then the 3Com devices probably don't send CDP or LLDP information to the switch, so the switch does not know about these neighbours.
Indeed it's possible that the 3Com devices are too old to support one of these discovery protocols (or running software that doesn't support it). Or perhaps CDP/LLDP is supported on them, but disabled in configuration. That's something you would have to look into.

Closing ticket as this is not an issue in SNMP::Info or in Netdisco itself.

**Closed by JeroenvIS** 2019-03-12 14:29 UTC
